[package]
name = "rust-dll-init"
version = "0.1.0"
authors = ["Rolf Karp <rolf.karp@gmail.com>"]
publish = false

[dependencies]
winapi = "0.2.8"
kernel32-sys = "0.2.2"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true
